### ISSUE TITLE
Support `config.json` without config key/choose default Python version

### ISSUE THREAD

**Issue by wfleming** [noqcks/codeclimate-bandit#3]
The `config.json` won't contain a `config` key unless a user specifies one in `.codeclimate.yml`, which isn't generally required. So with a simple config like

```
plugins:
  bandit:
    enabled: true
```

The plugin crashes:

```
Starting analysis
Running bandit: Done!
error: (CC::CLI::Analyze::EngineFailure) engine bandit failed with status 1 and stderr
Traceback (most recent call last):
  File "/usr/src/app/run.py", line 31, in <module>
    if config["config"].get("python_version"):
KeyError: 'config'
```

Code Climate encourages plugins to use reasonable defaults as much as possible to simplify setup for end-users. Preferably the plugin wouldn't require the user to specify any python version, and would work fine when this value wasn't specified in a `.codeclimate.yml`.

**Comment by noqcks** [comment]
Good call!

Defaulting to Python 3 when no `python_version`/`config` is set

Added in 94cf58b
