### ISSUE TITLE
Develop a more unique fingerprint scheme

### ISSUE THREAD

**Issue by wfleming** [noqcks/codeclimate-bandit#4]
The `test_id` field from Bandit doesn't seem appropriate to use for Code Climate's `fingerprint`. AFAICT, the `test_id` is a basically an abstract code that maps to the `test_name`, which means that different instances of the same check being reported on the different pieces of code end up getting the same `test_id`/`fingerprint`.

Semantically, Code Climate expects `fingerprint` to identify a single instance of a check, and we use that field to do things like determine if an issue is actually new on a PR or whether it already existed but might have simply moved location due to code changes. So using `test_id` as this value will effectively prevent Code Climate from reporting new issues from bandit on a user's PR if the same kind of issue already exists somewhere else in their codebase.

`fingerprint` is a heuristic, so there are different choices you can make for what to use as input in the identification. E.g. on some of the engines we maintain, for checks that always report on a method name we calculate the fingerprint as a hash of something like `md5(file_name + ":" + check_name + ":" method_name)`, in other cases we hash the actual code the issue was reported on. Hashing on the actual code is a little more liable to show an issue as "new" when somebody edits code within the area affected by the issue without changing the actual issue, but for security-related issues like what Bandit scans for I tend to think leaning towards ensuring more visibility/uniqueness for each issue is a good thing. So in your case I'd suggest calculating a hash from a combination of the `test_id` and the `code` from Bandit's JSON report (and maybe `file_name` as well in case a problematic one-liner is repeated across files), but maybe you have a better set of attributes in mind that would be an appropriate heuristic.

**Comment by noqcks** [comment]
Thanks for the detailed explanation @wfleming 

I think a hash of `test_id`, `code`, and `file_name` make the most sense to me. 

I've added this in 6f15a22
